### ISSUE TITLE
大牛，项目有严重问题啊

### ISSUE THREAD

**Issue by JamhonyZ** [immustard/MSTImagePickerController#1]
我的项目里导入你 MSTImagePickerController之后，WKWebView出现显示出错。
刚刚试了一下再你这个源码基础里 写一个浏览器的类WKWebViewVC，简单实现
WKWebView *wbView = [[WKWebView alloc] initWithFrame:self.view.bounds];
    [wbView loadRequest:[NSURLRequest requestWithURL:[NSURL URLWithString:@"https://www.baidu.com/"]]];
    [self.view addSubview:wbView];
然后将WKWebViewVC作为window的根控制器，也依然会出现WKContentView的子视图位置偏移。

**Comment by immustard** [comment]
实在抱歉，现在才来看这个问题。
问题已经解决了。是其中一个工具类文件的问题。
